### ISSUE TITLE
unicodeToBijoy("রিপোর্ট") throws RangeError (index)

### ISSUE THREAD

**Issue by 7ANV1R** [fahidsarker/bijoy_helper#1]
RangeError (index): Invalid value: Not in inclusive range 0..7: 8

#Stacktrace

      #1      _rearrangeUnicodeStr (package:bijoy_helper/executors.dart:38:35)
      #2      _toBijoyInner (package:bijoy_helper/executors.dart:66:10)
      #3      _toBijoy (package:bijoy_helper/executors.dart:82:15)
      #4      unicodeToBijoy (package:bijoy_helper/bijoy_helper.dart:15:10)
      
      
I think it's having hard time with "র্" (রেফ).

**Comment by fahidsarker** [comment]
The latest commit should fix the issue. Try version 1.0.1
